// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderHub.Infrastructure.Persistence;

#nullable disable

namespace OrderHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmtDbContext))]
    [Migration("20260902172440_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("OrderHub.Domain.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("OrderHub.Domain.BoardComponent", b =>
                {
                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlacementCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("BoardId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("BoardComponents");
                });

            modelBuilder.Entity("OrderHub.Domain.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Components");
                });

            modelBuilder.Entity("OrderHub.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderHub.Domain.OrderBoard", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BoardQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId", "BoardId");

                    b.HasIndex("BoardId");

                    b.ToTable("OrderBoards");
                });

            modelBuilder.Entity("OrderHub.Domain.BoardComponent", b =>
                {
                    b.HasOne("OrderHub.Domain.Board", "Board")
                        .WithMany("BoardComponents")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderHub.Domain.Component", "Component")
                        .WithMany("BoardComponents")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("OrderHub.Domain.OrderBoard", b =>
                {
                    b.HasOne("OrderHub.Domain.Board", "Board")
                        .WithMany("OrderBoards")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderHub.Domain.Order", "Order")
                        .WithMany("OrderBoards")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderHub.Domain.Board", b =>
                {
                    b.Navigation("BoardComponents");

                    b.Navigation("OrderBoards");
                });

            modelBuilder.Entity("OrderHub.Domain.Component", b =>
                {
                    b.Navigation("BoardComponents");
                });

            modelBuilder.Entity("OrderHub.Domain.Order", b =>
                {
                    b.Navigation("OrderBoards");
                });
#pragma warning restore 612, 618
        }
    }
}
